<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Log In  Sign Up_verification_code</name>
   <tag></tag>
   <elementGuidId>1f51501d-5bda-41f5-aa3f-9a6ced2cccb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#verification_code</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='verification_code']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e57a465f-fabe-4139-b982-c11a827a6a09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4304c129-92e8-42c2-8559-13bbc6d5af3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>verification_code</value>
      <webElementGuid>89476422-51a2-4e90-8a2a-703d085eeb5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>verification_code</value>
      <webElementGuid>927d742d-ecc6-4513-add3-8eb59aef9697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>inputNumOnly(this)</value>
      <webElementGuid>86c7acc4-1608-42cb-b8e2-fa4a965466aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>keyupHandler(this)</value>
      <webElementGuid>3ea4d78a-b848-4b34-8b16-49f6f0571368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;verification_code&quot;)</value>
      <webElementGuid>ddfed0ab-604e-487f-80da-dd65fe37e2b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='verification_code']</value>
      <webElementGuid>2a1f501c-42ed-4196-9d8c-fbde6038aaa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='post_login']/div[2]/div/input</value>
      <webElementGuid>4e53d2d8-7b3d-479d-aff7-e5c096bcdb55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>2cf95da1-a7bb-4ffa-ae58-ccd40a4780e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'verification_code' and @id = 'verification_code']</value>
      <webElementGuid>bbf0b981-3ffe-47c4-b91c-32206177ccf9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
