<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Label_Profile_Name</name>
   <tag></tag>
   <elementGuidId>06ac6747-8c3f-405b-856f-92f6a60f6591</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='How to pay for your loan?'])[1]/following::span[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.username</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>10bc56e0-5ccd-4ae3-a828-f7e1ed885bea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>3ce7bb59-f40d-4ebc-bca4-59d926b9aded</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>44113</value>
      <webElementGuid>f7c006c9-c969-48c3-9caf-ba4228cbfad3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> FirstnameDummy MiddlenameDummy LastnameDummy</value>
      <webElementGuid>32115c02-6569-4499-904c-95827d85e761</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;body-bg&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;wrapper person&quot;]/div[@class=&quot;part01 clearfix&quot;]/div[@class=&quot;col-sm-12 col-lg-4 wap-mb20&quot;]/div[@class=&quot;part01-txt&quot;]/div[1]/span[@class=&quot;username&quot;]</value>
      <webElementGuid>3b21ee19-7d16-4e1e-84a5-7afa01177ce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>31ca26f0-f168-42b5-ac35-7229c9547344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>305fea80-c0a9-4188-884f-c7c7ced7e717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>44113</value>
      <webElementGuid>90a7ea25-3593-4439-88f9-07af7df703cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> FirstnameDummy MiddlenameDummy LastnameDummy</value>
      <webElementGuid>38774f06-5a68-456f-a89d-88cf960eb118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;body-bg&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;wrapper person&quot;]/div[@class=&quot;part01 clearfix&quot;]/div[@class=&quot;col-sm-12 col-lg-4 wap-mb20&quot;]/div[@class=&quot;part01-txt&quot;]/div[1]/span[@class=&quot;username&quot;]</value>
      <webElementGuid>1e8a8237-1171-45fc-9680-b183fab8672a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How to pay for your loan?'])[1]/following::span[1]</value>
      <webElementGuid>dd5c7c5c-ef97-4e8c-9122-96c5a2794c70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lv.Max'])[1]/preceding::span[1]</value>
      <webElementGuid>067aea83-fe88-471c-ba9e-5c63696ccea5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone Number : +63 9174432720'])[1]/preceding::span[2]</value>
      <webElementGuid>405d44e0-d0bb-4fe3-9f5e-42c4c7be446e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='FirstnameDummy MiddlenameDummy LastnameDummy']/parent::*</value>
      <webElementGuid>001cf792-111a-4b5d-a529-a742ca851c6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>afefae28-141e-4b6a-8688-53db6cdc392b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' FirstnameDummy MiddlenameDummy LastnameDummy' or . = ' FirstnameDummy MiddlenameDummy LastnameDummy')]</value>
      <webElementGuid>defe6527-27a5-460d-a939-543d3ea0b479</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
