<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_step2_Next</name>
   <tag></tag>
   <elementGuidId>bf956899-520a-49d2-a9fe-5336ed524944</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.focus</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='submit_store()']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'NEXT' or . = 'NEXT')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NEXT</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'NEXT')]</value>
   </webElementXpaths>
</WebElementEntity>
