<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_input_step1_Warehouse_City_Address</name>
   <tag></tag>
   <elementGuidId>9def2667-8999-4adc-8453-f5624201e095</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.q_txt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[7]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
</WebElementEntity>
