<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_input_step2_Gender</name>
   <tag></tag>
   <elementGuidId>d60bb44a-8079-4a29-b371-87f3d7d69275</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.q_txt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[8]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
</WebElementEntity>
