<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_select_step3_PersonalReference1_Relation</name>
   <tag></tag>
   <elementGuidId>e3cf6073-9e9e-4f65-aae6-2235eba5fbb6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li[value=&quot;Father&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//li[@value='Father'])[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//li[@value = 'Father']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Father</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//li[@value='Father'])[1]</value>
   </webElementXpaths>
</WebElementEntity>
