<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_step3_PersonalReference4_Name</name>
   <tag></tag>
   <elementGuidId>7cf39918-4031-42af-ae5d-4e7c6e1e55b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;contact_4[name]&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='contact_4[name]']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@name = 'contact_4[name]']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>contact_4[name]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='contact_4[name]']</value>
   </webElementXpaths>
</WebElementEntity>
