<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_Log In Sign Up</name>
   <tag></tag>
   <elementGuidId>dec66613-f2ac-4760-b33a-04f6ae736a3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='login_dev']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'login_dev']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#login_dev</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>789754b6-3dc3-4f16-b10b-e217f453f8fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn login_dev</value>
      <webElementGuid>71812dc2-b59c-47ce-9a83-9cfa4557f3f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5e42bb3b-dcb2-46b5-a1d2-867bad965155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>submita()</value>
      <webElementGuid>7f5a2688-7501-49e3-93aa-deb534028df6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login_dev</value>
      <webElementGuid>3f46126a-7920-4568-b381-d4d520b041ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Log In / Sign Up</value>
      <webElementGuid>e4ac9dfe-8e82-4cbf-b88e-286ef428a64f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login_dev&quot;)</value>
      <webElementGuid>68cd4162-574a-4afd-a747-ecbdcfa59243</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='login_dev']</value>
      <webElementGuid>960e60a3-6512-4283-8ee6-2dda6e23cf5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='post_login']/div[5]/button</value>
      <webElementGuid>e865080a-aa4d-4eab-961e-0019d7ce92f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='terms of use'])[1]/following::button[1]</value>
      <webElementGuid>0650bad7-f52c-41cf-9c7d-01544ff39ef6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go to lazada to authorize'])[1]/preceding::button[1]</value>
      <webElementGuid>c54e215f-550d-4e27-9f96-8f7ef321a212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/button</value>
      <webElementGuid>770526e3-1f03-4b0d-b667-4dea36b37b02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'login_dev' and (text() = 'Log In / Sign Up' or . = 'Log In / Sign Up')]</value>
      <webElementGuid>67106cdb-0222-4608-936d-14ac6d361f7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
