<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_LogInSignUp_OTP6</name>
   <tag></tag>
   <elementGuidId>263708aa-ea5f-4dc1-9313-5aab9fcf8d55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tb5']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'tb5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tb5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f5d6d0c2-ddd2-4fbc-81b1-1b98c45c4d63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tb-code</value>
      <webElementGuid>9b2cbff5-b4fc-414c-b0a7-89d0121bf33b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>04beb64a-f2f4-4f2a-8c99-9b3198d3f733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tb5</value>
      <webElementGuid>73b2c692-878b-46a0-b692-2d5b0330f90c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tb5&quot;)</value>
      <webElementGuid>30633090-c453-4728-9f22-8fdfbe779b00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tb5']</value>
      <webElementGuid>c9e10dc1-cb4a-4489-ba75-1bd01e19fdee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='post_login']/div[2]/div/div/input[6]</value>
      <webElementGuid>393914e1-2384-485c-ab5a-5bb12f4589a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[6]</value>
      <webElementGuid>f5758cae-0e3e-4df3-bbc7-3b2171146f50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'tb5']</value>
      <webElementGuid>7121074c-9c1a-4307-a0a0-7072f77d4013</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
