<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chatbot_field</name>
   <tag></tag>
   <elementGuidId>72aaae20-07bb-4134-bad7-e4e3439c9158</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ThreadHistoryFetcher__ScrollToWrapper-mpap2q-1.kYFmaz.messages-scroll-container-utv</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='current-view-component']/div/main/div[2]/div/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;current-view-component&quot;)/div[@class=&quot;VisitorWidgetStyleWrapper__WidgetStyleWrapper-m976i2-0 dogESN&quot;]/main[@class=&quot;VisitorWidgetStyleWrapper__WidgetContentStyleWrapper-m976i2-1 jVsMxE chat-widget&quot;]/div[@class=&quot;VisitorWidget__WidgetBodyDiv-sc-132xu91-0 jxoBng&quot;]/div[@class=&quot;UnifiedThreadViewWrapperWithDragUpload__UnifiedThreadViewWrapper-s4ctvh-0 ftjQdo&quot;]/div[@class=&quot;ThreadHistoryFetcher__ScrollToWrapper-mpap2q-1 kYFmaz messages-scroll-container-utv&quot;][count(. | //*[(text() = concat(&quot;Got any questions? I&quot; , &quot;'&quot; , &quot;m happy to help.&quot;) or . = concat(&quot;Got any questions? I&quot; , &quot;'&quot; , &quot;m happy to help.&quot;)) and @ref_element = 'Object Repository/Desktop_Home_Page/iframe']) = count(//*[(text() = concat(&quot;Got any questions? I&quot; , &quot;'&quot; , &quot;m happy to help.&quot;) or . = concat(&quot;Got any questions? I&quot; , &quot;'&quot; , &quot;m happy to help.&quot;)) and @ref_element = 'Object Repository/Desktop_Home_Page/iframe'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0bbf0861-d252-4c34-b1d5-9cfdb870425d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ThreadHistoryFetcher__ScrollToWrapper-mpap2q-1 kYFmaz messages-scroll-container-utv</value>
      <webElementGuid>3bb09716-d65c-4486-bfb5-d950f2986f45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Got any questions? I'm happy to help.</value>
      <webElementGuid>eb9cc0f2-3dc9-4395-a7ee-8712266c5432</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;current-view-component&quot;)/div[@class=&quot;VisitorWidgetStyleWrapper__WidgetStyleWrapper-m976i2-0 dogESN&quot;]/main[@class=&quot;VisitorWidgetStyleWrapper__WidgetContentStyleWrapper-m976i2-1 jVsMxE chat-widget&quot;]/div[@class=&quot;VisitorWidget__WidgetBodyDiv-sc-132xu91-0 jxoBng&quot;]/div[@class=&quot;UnifiedThreadViewWrapperWithDragUpload__UnifiedThreadViewWrapper-s4ctvh-0 ftjQdo&quot;]/div[@class=&quot;ThreadHistoryFetcher__ScrollToWrapper-mpap2q-1 kYFmaz messages-scroll-container-utv&quot;]</value>
      <webElementGuid>9744d6d8-b034-4826-8a55-b3af80ee848a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Desktop_Home_Page/iframe</value>
      <webElementGuid>45a3cc8d-a977-47c0-95d5-d7f321b1baf2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='current-view-component']/div/main/div[2]/div/div</value>
      <webElementGuid>407811eb-768e-44a0-8efc-f372d8f2a18a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('We', &quot;'&quot;, 'll return tomorrow at 09:00 AM')])[1]/following::div[4]</value>
      <webElementGuid>0b5f6d60-72e1-467b-bd66-a85f112ca164</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kayamo'])[1]/following::div[5]</value>
      <webElementGuid>587496a1-edc4-498b-9db4-bb706e53fcce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div[2]/div/div</value>
      <webElementGuid>17612ae6-9348-48cc-a296-219d041418c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;Got any questions? I&quot; , &quot;'&quot; , &quot;m happy to help.&quot;) or . = concat(&quot;Got any questions? I&quot; , &quot;'&quot; , &quot;m happy to help.&quot;))]</value>
      <webElementGuid>af5fa0c8-ff5e-4847-a407-8f591a9a6af1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
