<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>error_This verification code has expired</name>
   <tag></tag>
   <elementGuidId>2d540551-74a3-4d41-a282-5129e4255f9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;layui-layer1&quot;)/div[@class=&quot;layui-layer-content layui-layer-padding&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.layui-layer-content.layui-layer-padding</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0759cae9-0565-4467-bf0f-4f716d6d1969</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>layui-layer-content layui-layer-padding</value>
      <webElementGuid>33fa799a-2c6e-4f3a-917a-ccfe7bfdb327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This verification code has expired.</value>
      <webElementGuid>f098391d-5060-4157-a00c-def01647ac67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layui-layer1&quot;)/div[@class=&quot;layui-layer-content layui-layer-padding&quot;]</value>
      <webElementGuid>2f30b1c8-88af-4b85-ae85-df3f7c4a8458</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='']</value>
      <webElementGuid>2a36a429-b848-4850-9af5-387bfe9edb74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layui-layer1']/div</value>
      <webElementGuid>ae6899c9-fd73-4034-acf8-a2c5d32e2766</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YES'])[1]/following::div[6]</value>
      <webElementGuid>d2e182f6-b24e-4c64-bd53-6c6bbcdb82e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NO'])[1]/following::div[6]</value>
      <webElementGuid>67df46b9-2562-4bfd-9e8c-e7758eceea1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='This verification code has expired.']/parent::*</value>
      <webElementGuid>35e96c47-1497-41b7-93dc-6b4a277b6a6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div</value>
      <webElementGuid>5d8b8d52-2906-4af7-aefd-bd373e2fe2e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'This verification code has expired.' or . = 'This verification code has expired.')]</value>
      <webElementGuid>05a6215e-6081-4481-99df-3ea789a12286</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
