<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_LogInSignUp_OTP3</name>
   <tag></tag>
   <elementGuidId>20f06fe5-d0a9-4240-9d5d-2b4a14aab3da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tb2']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'tb2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tb2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f16494b5-9b64-46bf-8867-5f386b39ebed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tb-code</value>
      <webElementGuid>d9a9be0f-28d0-404c-82ce-cddc1e4a748f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0ff4133d-51f3-4daa-8379-d784ae5031bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tb2</value>
      <webElementGuid>67e7ab9b-6147-491d-830e-0267800956e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tb2&quot;)</value>
      <webElementGuid>ae37fb4b-836f-4971-80d4-a1f974280d5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tb2']</value>
      <webElementGuid>b2d3cdd4-1622-4472-a189-f7bf806713f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='post_login']/div[2]/div/div/input[3]</value>
      <webElementGuid>fb240050-e827-438f-8537-fdbc2f024564</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>fd91a094-b969-4f1c-ae28-e3cb5089d852</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'tb2']</value>
      <webElementGuid>de42e436-c463-4299-8dd1-624545a7717a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
