<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_LogInSignUp_OTP1</name>
   <tag></tag>
   <elementGuidId>2f4d1b08-cecf-43f1-905b-d4663bb4cc30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tb0']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'tb0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tb0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1ce61202-6a7b-4ec7-b011-f10de3b43b57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tb-code</value>
      <webElementGuid>0fd98637-a96b-401c-a43f-cd9cb35d0564</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5d1f8b4b-8606-4ee6-af98-1b1976cfa7c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tb0</value>
      <webElementGuid>0a2f045c-b251-4a2c-86d9-556ce93d56f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tb0&quot;)</value>
      <webElementGuid>f323a1f2-3a15-4427-94bf-3d1c6c445245</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tb0']</value>
      <webElementGuid>aaca8d38-32ab-4649-b6bd-08c16418f4e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='post_login']/div[2]/div/div/input</value>
      <webElementGuid>07cf7864-48ce-44d4-8a67-15c98b3fc0e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>4fa0c3b7-3112-4223-b1f4-8e0d17c91721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'tb0']</value>
      <webElementGuid>3c896663-b600-48a6-9185-c32f1163c1c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
