<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_LogInSignUp_OTP5</name>
   <tag></tag>
   <elementGuidId>4353000a-b57b-436b-b6ac-1832aea79fc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tb4']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'tb4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tb4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>06cc6827-772b-43d7-ab56-4f8981d08ce1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tb-code</value>
      <webElementGuid>6dd01c2e-35e8-4ebf-8794-53f787c29198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cc2229fc-de86-42d8-b8ca-9f4fdf382b79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tb4</value>
      <webElementGuid>bd8d7b27-0b36-49d9-a4d1-bb19db0bf08c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tb4&quot;)</value>
      <webElementGuid>3c200a40-b0bb-44bb-8aed-0f4cbd118e7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tb4']</value>
      <webElementGuid>0554a4a8-750f-4eb5-8dee-31a8e207071e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='post_login']/div[2]/div/div/input[5]</value>
      <webElementGuid>1a845d7e-6706-4491-b4ae-619fd224a898</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[5]</value>
      <webElementGuid>c3781ea8-afdf-481b-ab54-b7674f60b7ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'tb4']</value>
      <webElementGuid>9b7b884a-10b9-43d4-ada7-9637fd29c279</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
