<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>This is an end to end test for signup or login to logout.</description>
   <name>E2E_Signup_Login_Logout</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient>carl.carriedo@kayamo.com;</mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>3bf4ae6f-78a2-4572-9ffe-36873dee74be</testSuiteGuid>
   <testCaseLink>
      <guid>f5a01ce9-40bf-4ceb-9d4c-3e4edfcdcd24</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/KayamoSite_Functional/KS_TC002_Signup_Login_Valid_Login</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>68397658-0561-44e1-8143-4b22b9e2328d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>385ccad8-5af5-454b-8846-088295945a66</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c7a260e-f9df-4f85-8d71-029447c549ba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc3d1292-88f2-4e39-91d0-891ea6b579e2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa72d9c7-53e3-4ef1-a71f-5f584d85545c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b3e8ed7-b6ac-4bf3-a9b3-1538c3da0c32</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d86d24ad-8f34-48d9-a4ea-e03c78a75813</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b78ce092-3848-4df6-a6c2-76e1c2c4ec9d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86ab8ad0-09d0-4c40-a643-3a06ae4cfb81</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf9b5a0a-17b5-45cd-a90b-0cee7ad43a82</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>26276046-c72e-4d66-9aee-2c2bbb6d052c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/KayamoSite_Functional/KS_Logout</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
