<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Loan_Number</name>
   <tag></tag>
   <elementGuidId>3c087397-cc19-4608-8c33-828024463b66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#loan_number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='loan_number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2e44ae12-866c-46be-897a-a41520d1daa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6755fb95-07dc-4b72-a7c3-ede2b580663e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loan_number</value>
      <webElementGuid>cfdf2a3a-3608-4822-ab84-d7312914c8a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>loan_number</value>
      <webElementGuid>e18b9765-1874-475f-b319-59de10c7512b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>9e6422b2-71ef-4735-a307-db2700bd3c89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loan_number&quot;)</value>
      <webElementGuid>8a5cc0f1-9783-4ada-88d5-3392f019810a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='loan_number']</value>
      <webElementGuid>67e8b5f0-3b70-46be-a121-d2d6384d7d67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div/div/input</value>
      <webElementGuid>dc7b8013-15ab-41c5-ae82-5b2e97b9ed11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>641cdf61-52f0-4651-bfcb-0523482e0048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'loan_number' and @name = 'loan_number']</value>
      <webElementGuid>0422e0a7-8f5c-442d-bed4-25f3d4fd4a77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
