<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>submenu_All_Loans</name>
   <tag></tag>
   <elementGuidId>0abace11-ca1a-4419-8f72-86a818af5dc3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.active > ul.nav.child_menu > li > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sidebar-menu']/div/ul/li[2]/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>258c660b-6999-448f-bc3b-2f8b29f0c7e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://uat-admin.kayamo.com.ph/admin/lazada/loan</value>
      <webElementGuid>d6f92789-a1ca-4fd7-9c9c-89e8f1026a34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All loans</value>
      <webElementGuid>3fb451c8-4659-49c7-9e40-93c4bad13c7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar-menu&quot;)/div[@class=&quot;menu_section&quot;]/ul[@class=&quot;nav side-menu&quot;]/li[@class=&quot;active&quot;]/ul[@class=&quot;nav child_menu&quot;]/li[1]/a[1]</value>
      <webElementGuid>0060617d-9226-4dc0-b9a1-e016dd39aa1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebar-menu']/div/ul/li[2]/ul/li/a</value>
      <webElementGuid>81ec3e44-ba77-46e8-83e5-7bcaa48b9df2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'All loans')])[2]</value>
      <webElementGuid>f3652c62-e7ba-4770-bb48-15b8cd6feb32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Historical records'])[1]/following::a[2]</value>
      <webElementGuid>c32a3987-64cf-457e-aac9-8f48e24960ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Merchant loan allocation'])[1]/preceding::a[1]</value>
      <webElementGuid>95af59c2-8908-418d-a81e-53c62524f18a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='last trial'])[1]/preceding::a[3]</value>
      <webElementGuid>b260fe34-3a21-46b9-a348-acd19000c019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://uat-admin.kayamo.com.ph/admin/lazada/loan')]</value>
      <webElementGuid>1e254992-8dc8-41f3-b304-cfd27e60ff5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li/a</value>
      <webElementGuid>7892c6e5-f41f-483c-b0f6-aec60f3c09e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://uat-admin.kayamo.com.ph/admin/lazada/loan' and (text() = 'All loans' or . = 'All loans')]</value>
      <webElementGuid>c2e0d1c9-bee7-439d-9ddc-2ec0022f244e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
